/*
 * account.java
 *
 * Created on March 22, 2012, 7:41 PM
 */

package clinic;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author  Administrator
 */
public class account extends javax.swing.JFrame {
       String f,g,h,i,j,a,b,c; 
       account_report ar=new account_report(i,a,g,h);
       boolean arvi=ar.isVisible();
    /** Creates new form account */
    public account() {
        initComponents();
    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlname = new javax.swing.JPanel();
        optdate = new javax.swing.JRadioButton();
        optmonth = new javax.swing.JRadioButton();
        optyear = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbomonth = new javax.swing.JComboBox();
        cbodate = new javax.swing.JComboBox();
        cboyear = new javax.swing.JComboBox();
        lblyear = new javax.swing.JLabel();
        lblmonth = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        btnshow = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("ACCOUNT REPORT");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlname.setName("pnlname"); // NOI18N

        optdate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        optdate.setText("Date");
        optdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        optdate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        optdate.setName("optdate"); // NOI18N
        optdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optdateActionPerformed(evt);
            }
        });

        optmonth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        optmonth.setText("Month");
        optmonth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        optmonth.setMargin(new java.awt.Insets(0, 0, 0, 0));
        optmonth.setName("optmonth"); // NOI18N
        optmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmonthActionPerformed(evt);
            }
        });

        optyear.setFont(new java.awt.Font("Times New Roman", 0, 14));
        optyear.setText("Year");
        optyear.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        optyear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        optyear.setName("optyear"); // NOI18N
        optyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optyearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlnameLayout = new org.jdesktop.layout.GroupLayout(pnlname);
        pnlname.setLayout(pnlnameLayout);
        pnlnameLayout.setHorizontalGroup(
            pnlnameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlnameLayout.createSequentialGroup()
                .addContainerGap()
                .add(optdate)
                .add(41, 41, 41)
                .add(optmonth)
                .add(30, 30, 30)
                .add(optyear)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlnameLayout.setVerticalGroup(
            pnlnameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlnameLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlnameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(optdate)
                    .add(optmonth)
                    .add(optyear))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbomonth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cbomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        cbomonth.setName("cbomonth"); // NOI18N

        cbodate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cbodate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbodate.setName("cbodate"); // NOI18N

        cboyear.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cboyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        cboyear.setName("cboyear"); // NOI18N

        lblyear.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblyear.setText("Year");
        lblyear.setName("lblyear"); // NOI18N

        lblmonth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblmonth.setText("Month");
        lblmonth.setName("lblmonth"); // NOI18N

        lbldate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lbldate.setText("Date");
        lbldate.setName("lbldate"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(58, 58, 58)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbldate)
                    .add(cbodate, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(lblmonth))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(cbomonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(cboyear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(lblyear)))
                .add(152, 152, 152))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbldate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblmonth)
                    .add(lblyear))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbodate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbomonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cboyear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnshow.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnshow.setText("Show");
        btnshow.setName("btnshow"); // NOI18N
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnback.setText("Back");
        btnback.setName("btnback"); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(pnlname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(btnshow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(25, 25, 25)
                        .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnshow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(70, 70, 70))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
// TODO add your handling code here:
         ar.setVisible(false);
         this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void optyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optyearActionPerformed
// TODO add your handling code here:
        lbldate.setVisible(false);
        lblmonth.setVisible(false);
        cbodate.setVisible(false);
        cbomonth.setVisible(false);
        optdate.setSelected(false);
        optmonth.setSelected(false);
        lblyear.setVisible(true);
        cboyear.setVisible(true);
        ar.setVisible(false);
        
    }//GEN-LAST:event_optyearActionPerformed

    private void optmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmonthActionPerformed
// TODO add your handling code here:
        lbldate.setVisible(false);
        cbodate.setVisible(false);
        optdate.setSelected(false);
        optyear.setSelected(false);
        lblmonth.setVisible(true);
        cbomonth.setVisible(true);
        lblyear.setVisible(true);
        cboyear.setVisible(true);
        ar.setVisible(false);
    }//GEN-LAST:event_optmonthActionPerformed

    private void optdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optdateActionPerformed
// TODO add your handling code here:
           optmonth.setSelected(false);
        optyear.setSelected(false);
            lbldate.setVisible(true);
        cbodate.setVisible(true);
         lblmonth.setVisible(true);
        cbomonth.setVisible(true);
        lblyear.setVisible(true);
        cboyear.setVisible(true);
        ar.setVisible(false);
        
    }//GEN-LAST:event_optdateActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
// TODO add your handling code here:
      
        f=(String)cbodate.getSelectedItem();
        g=(String)cbomonth.getSelectedItem();
        h=(String)cboyear.getSelectedItem();
        i=f+"-"+g+"-"+h;
        j=g+"-"+h;
        boolean date,month,year;
        a=optdate.getText();
        b=optmonth.getText();
        c=optyear.getText();
        date=optdate.isSelected();
        month=optmonth.isSelected();
        year=optyear.isSelected();
         if(date)
          {
            if(arvi==false)
            {
             ar=new account_report(i,a,g,h);
             ar.setVisible(true);
             arvi=true;
            }
            else
            {
             arvi=ar.isVisible();
             if(arvi==false)
             {    
              ar=new account_report(i,a,g,h);
              ar.setVisible(true);
              arvi=true;
             }
             else
             {
              ar.requestFocus();  
             }    
            }  
          }   
          else if(month)
          {
          
           if(arvi==false)
            {
             ar=new account_report(j,b,g,h);
             ar.setVisible(true);
             arvi=true;
            }
            else
            {
             arvi=ar.isVisible();
             if(arvi==false)
             { 
              ar=new account_report(j,b,g,h);   
              ar.setVisible(true);
              arvi=true;
             }
             else
             {
              ar.requestFocus();  
             }    
            }  
          }   
          else if(year)
          { 
           
           if(arvi==false)
           {
             ar=new account_report(h,c,g,h);
             ar.setVisible(true);
             arvi=true;
           }
           else
           {
             arvi=ar.isVisible();
             if(arvi==false)
             { 
              ar=new account_report(h,c,g,h);   
              ar.setVisible(true);
              arvi=true;
             }
             else
             {
              ar.requestFocus();  
             }    
            }  
          }
       
        else
        {
         JOptionPane.showMessageDialog(this,"First Select data ");   
        }   
    }//GEN-LAST:event_btnshowActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnshow;
    private javax.swing.JComboBox cbodate;
    private javax.swing.JComboBox cbomonth;
    private javax.swing.JComboBox cboyear;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblmonth;
    private javax.swing.JLabel lblyear;
    private javax.swing.JRadioButton optdate;
    private javax.swing.JRadioButton optmonth;
    private javax.swing.JRadioButton optyear;
    private javax.swing.JPanel pnlname;
    // End of variables declaration//GEN-END:variables
    
}
