  /*
 * card.java
 *
 * Created on February 4, 2012, 7:17 AM
 */

package clinic;


import java.io.InputStream;
import javax.swing.*;
import java.sql.*;

import java.util.Date;
import java.text.*;
import java.util.*;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JRPrintPage;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author  Administrator
 */
public class card extends javax.swing.JFrame {     
    Date date=new Date();
     String s1,s2,s5;
     int s3,s4; 
     String name,allergy,gender,code,diesease,treatement;
     int age, amount;
   
     tablet t=new tablet();
     boolean tvi=t.isVisible();
     Diesease di=new Diesease();
     
     boolean dvi=di.isVisible();
     patientrecords prs=new patientrecords(name,allergy,gender,code,age);
     boolean prsvi=prs.isVisible();
     
     int rs=0,rs1=0,rem=0;
    /** Creates new form card */
       String c=""; 
    String t1,t2,t3,t4;
           int t5,t6,t8,t7,t10=0;
    public card(String code,String name,String gender,String allergy,int age) {
        initComponents();
         lbldatedisplay.setText(""+date);
        txtcode.setText(code);
        txtname.setText(name);
        txtgender.setText(gender);
        txtallergy.setText(allergy);
        txtage.setText(""+age);
          int a=0;
        txtamount.setText(""+a);
    
        c=txtcode.getText();
      
    }
  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblallergy = new javax.swing.JLabel();
        txtallergy = new javax.swing.JTextField();
        lblcode = new javax.swing.JLabel();
        lbldatedisplay = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiesease = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttreatement = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        lbldiesease = new javax.swing.JLabel();
        lbltreatement = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblcard = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblbill = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpaid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        lblamount = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnhistory = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        lbleamount = new javax.swing.JLabel();
        lblreminder = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Card");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbldate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldate.setText("Date");
        lbldate.setName("lbldate"); // NOI18N

        txtcode.setEditable(false);
        txtcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcode.setBorder(null);
        txtcode.setName("txtcode"); // NOI18N

        lblname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblname.setText("Name");
        lblname.setName("lblname"); // NOI18N

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setBorder(null);
        txtname.setName("txtname"); // NOI18N

        Age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Age.setText("Age");
        Age.setName("lblage"); // NOI18N

        txtage.setEditable(false);
        txtage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtage.setBorder(null);
        txtage.setName("txtage"); // NOI18N

        lblgender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblgender.setText("Gender");

        txtgender.setEditable(false);
        txtgender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtgender.setBorder(null);
        txtgender.setName("txtgender"); // NOI18N

        lblallergy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblallergy.setText("Allergy  :-");
        lblallergy.setName("lblallergy"); // NOI18N

        txtallergy.setEditable(false);
        txtallergy.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtallergy.setBorder(null);
        txtallergy.setName("txtallergy"); // NOI18N

        lblcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblcode.setText("Code");
        lblcode.setName("lblcode"); // NOI18N

        lbldatedisplay.setBackground(new java.awt.Color(233, 230, 212));
        lbldatedisplay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldatedisplay.setName("lbldatedisplay"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblallergy)
                    .add(lblname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbldate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbldatedisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 276, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 80, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblgender)
                    .add(lblcode)
                    .add(Age))
                .add(33, 33, 33)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtgender, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtage))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbldate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblcode)
                    .add(lbldatedisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblname)
                    .add(lblgender)
                    .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Age)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(11, 11, 11)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(lblallergy)
                                    .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(txtage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdiesease.setColumns(1);
        txtdiesease.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdiesease.setLineWrap(true);
        txtdiesease.setRows(1);
        txtdiesease.setTabSize(2);
        txtdiesease.setName("txtdiesease"); // NOI18N
        txtdiesease.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdieseaseFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(txtdiesease);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Disease");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });

        txttreatement.setColumns(1);
        txttreatement.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txttreatement.setLineWrap(true);
        txttreatement.setRows(1);
        txttreatement.setTabSize(2);
        txttreatement.setName("txttreatement"); // NOI18N
        txttreatement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttreatementFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(txttreatement);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Treatment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });

        lbldiesease.setForeground(new java.awt.Color(204, 0, 0));

        lbltreatement.setForeground(new java.awt.Color(204, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(67, 67, 67)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(26, 26, 26)
                            .add(lbldiesease, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(5, 5, 5)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(108, 108, 108))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(lbltreatement, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .add(18, 18, 18))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lbldiesease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(4, 4, 4)
                        .add(lbltreatement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .add(10, 10, 10))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        lblcard.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        lblcard.setForeground(new java.awt.Color(0, 153, 51));
        lblcard.setText("Patient Card");
        lblcard.setName("lblcard"); // NOI18N

        lblid.setName("lblid"); // NOI18N

        lblbill.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Visit No. :");

        txtbalance.setEditable(false);
        txtbalance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Balance");

        txtpaid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpaid.setEnabled(false);
        txtpaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpaidFocusLost(evt);
            }
        });
        txtpaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpaidKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Paid");

        txtamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtamount.setName("txtamount"); // NOI18N
        txtamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtamountFocusLost(evt);
            }
        });
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtamountKeyReleased(evt);
            }
        });

        lblamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblamount.setText("Amount");
        lblamount.setName("lblamount"); // NOI18N

        btnexit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnexit.setText("Back");
        btnexit.setName("btnexit"); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnhistory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnhistory.setText("History");
        btnhistory.setName("btnhistory"); // NOI18N
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.setName("btnsave"); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lbleamount.setForeground(new java.awt.Color(204, 0, 0));

        lblreminder.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        lblreminder.setForeground(new java.awt.Color(255, 51, 102));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
            .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(313, 313, 313)
                        .add(lblcard)
                        .add(63, 63, 63)
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(lblid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(125, 125, 125)
                                .add(lblreminder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblbill)))
                    .add(layout.createSequentialGroup()
                        .add(55, 55, 55)
                        .add(lblamount)
                        .add(33, 33, 33)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(txtamount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(41, 41, 41)
                                .add(jLabel2)
                                .add(13, 13, 13)
                                .add(txtpaid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(59, 59, 59)
                                .add(jLabel3)
                                .add(18, 18, 18)
                                .add(txtbalance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(lbleamount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(btnsave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(75, 75, 75)
                        .add(btnhistory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(76, 76, 76)
                        .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(79, 79, 79)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblcard)
                    .add(jLabel1)
                    .add(lblid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblbill)
                .add(7, 7, 7)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(lblreminder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28)))
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblamount)
                    .add(txtamount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(txtpaid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtbalance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbleamount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnexit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .add(btnhistory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnsave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusLost
// TODO add your handling code here:
        int amount;
        String amoun=txtamount.getText();
        if(!(amoun.equals("")))
        {
         amount=Integer.parseInt(amoun);
         txtpaid.setText(""+amount);
        }
        
     
    }//GEN-LAST:event_txtamountFocusLost

    private void txtpaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidKeyReleased
// TODO add your handling code here:
                
        String s=txtpaid.getText();
        if(!(s.equals("")))
        {
         int a=s.length()-1;
         int i=(int)s.charAt(a);
         if(!(i>47&&i<58))
        {
            JOptionPane.showMessageDialog(this,"Enter only number","Warning",JOptionPane.WARNING_MESSAGE);
            txtpaid.setText("");

         }

       
       }
        
    }//GEN-LAST:event_txtpaidKeyReleased

    private void txtpaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpaidFocusLost
// TODO add your handling code here:
    
                 
    }//GEN-LAST:event_txtpaidFocusLost

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
// TODO add your handling code here:
        
                
         String s=txttreatement.getText().trim();
                try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
           ResultSet rs2=st.executeQuery("select reference from refer");
            while(rs2.next()) {
                String refe=rs2.getString("reference");
                txttreatement.setText(txttreatement.getText()+""+refe+", ");
            }
            int vo=st.executeUpdate("delete from refer");
            st.close();
            con.close();
        } 
           catch(SQLException sq)
         {
              JOptionPane.showMessageDialog(this,"Database Error","Reference",JOptionPane.ERROR_MESSAGE);   
               
         }      
           catch(Exception e) {
            JOptionPane.showMessageDialog(this,"error occur"+e);
        }
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
// TODO add your handling code here:
        
                              String s=txtdiesease.getText().trim();
                try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
        ResultSet rs3=st.executeQuery("select reference from refer");
            while(rs3.next()) {
                String refe=rs3.getString("reference");
                txtdiesease.setText(txtdiesease.getText()+""+refe+", ");
            }
            int vo=st.executeUpdate("delete from refer");
            st.close();
            con.close();
        }  catch(SQLException sq)
         {
              JOptionPane.showMessageDialog(this,"Database Error","Reference",JOptionPane.ERROR_MESSAGE);   
             
         }
                
          catch(Exception e) {
            JOptionPane.showMessageDialog(this,"error occur"+e);
        } 
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
     if(tvi==false)
      {    
        t.setVisible(true);
        tvi=true;
      }
      else
       {
         tvi=t.isVisible();
         if(tvi==false)
          {    
           t.setVisible(true);
           tvi=true;
          }
         else
          {
           t.requestFocus();  
          }    
       }       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
     if(dvi==false)
      {    
       di.setVisible(true);
       dvi=true;
      }
      else
       {
        dvi=di.isVisible();
        if(dvi==false)
        {    
         di.setVisible(true);
         dvi=true;
        }
        else
        {
          di.requestFocus();  
        }    
       }   
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyReleased
// TODO add your handling code here:
        String s=txtamount.getText();
        if(!s.equals(""))
        {
         int a=s.length()-1;
         int i=(int)s.charAt(a);
         if(!(i>47&&i<58))
         {
            lbleamount.setText("Enter only number");
            
            txtamount.setText("");
         }
         else
        {
         lbleamount.setText("");
         txtpaid.setEnabled(true);
         }
       }
    }//GEN-LAST:event_txtamountKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO
//        txtreminder.setText("0");
        lbltreatement.setText("");
        lbldiesease.setText("");
        lbleamount.setText("");
          register r=new register();
          r.dispose();
        
         String b=txtcode.getText();
         int d=1,refe=0;
        lblbill.setVisible(false);
        String cod=txtcode.getText();
        try{
                       
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:rock");
        Statement st=con.createStatement();
        ResultSet rs3=st.executeQuery("select count(treatement_id)+1 from treatement where code='"+cod+"'");
        while(rs3.next())
        {
            d=rs3.getInt(1);
            lblid.setText(""+d); 
        }
         ResultSet rs4=st.executeQuery("select count(bill_id)+1 from treatement");
         while(rs4.next())
         {
           int e=rs4.getInt(1);
           lblbill.setText(""+e);
         }
         int f=d-1;
         if(!(f==0))
         {    
          ResultSet rs2=st.executeQuery("select balance from treatement where code='"+cod+"' and treatement_id="+f+"");  
          while(rs2.next()) 
             {
                refe=rs2.getInt("balance");
                txtbalance.setText(""+refe);
                txtpaid.setText("0");
             }
         }
         else
         {
                
                txtbalance.setText(""+refe);
                txtpaid.setText("0");
         }    
        st.close();
        con.close();
           
     }  catch(SQLException sq)
         {
              JOptionPane.showMessageDialog(this,"Database Error","Treatement",JOptionPane.ERROR_MESSAGE);   
              this.dispose(); 
         }
        catch(Exception e)
         {
          JOptionPane.showMessageDialog(this,"Error Occur"+e);   
         }
    
        
       
    }//GEN-LAST:event_formWindowOpened

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
       // TODO add your handling code here:
    int z=Integer.parseInt(lblid.getText());
    if(z>1)
     {   
       name=txtname.getText();
       allergy=txtallergy.getText();
       gender=txtgender.getText();
       code=txtcode.getText();
       age=Integer.parseInt(txtage.getText());
        if(prsvi==false)
        {  
         prs=new patientrecords(name,allergy,gender,code,age);   
         prs.setVisible(true);
         prsvi=true;
        }
        else
        {
         prsvi=prs.isVisible();
          if(prsvi==false)
           {
            prs=new patientrecords(name,allergy,gender,code,age);     
            prs.setVisible(true);
            prsvi=true;
           }
          else
          {
          prs.requestFocus();  
          }    
        }   
      }
      else
      {
          JOptionPane.showMessageDialog(this,"History not available");
      }   

    }//GEN-LAST:event_btnhistoryActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
// TODO add your handling code here:
           homepage hp=new homepage();
       
           t.setVisible(false);
           di.setVisible(false);
           prs.setVisible(false);
           hp.toBack();
           this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
       int amount,paid,balance;
       int l,m,o,p=0,n=0;
       int remin=0;
       String remind="01-jan-1995";  
       String reminds="01-jan-1995"; 
       int remindr=0,dell=0;
       
                        int zorro=0;
        t1=txtname.getText();
        t2=txtcode.getText();
        t3=txtdiesease.getText();
        t4=txttreatement.getText();
        t6=Integer.parseInt(lblid.getText());
        t7=Integer.parseInt(lblbill.getText());
        t8=Integer.parseInt(txtamount.getText()); 
        int pay=Integer.parseInt(txtpaid.getText());
        int t9=Integer.parseInt(txtbalance.getText());
        
         
       
       

               
        if(!(t3.equals("")||t4.equals("")||t8==0))
           { 
                    
//               remin=Integer.parseInt(txtreminder.getText());
               
                 amount=Integer.parseInt(txtamount.getText());
       paid=Integer.parseInt(txtpaid.getText());
       balance=Integer.parseInt(txtbalance.getText());
       
        if(amount==paid)
               {   
                if(balance==0)
                   {
                    txtbalance.setText("0");
                   }
                   else
                   {
                    txtbalance.setText(""+balance);
                   }
                 }
                else
                {
                 if(balance==0)
                  {
                   n=amount-paid;
                    txtbalance.setText(""+n);
                  }
                 else
                  {
                    n=balance+(amount-paid);      
                    txtbalance.setText(""+n);
                  }
                }

                        
            
           try
              { 

               
               
               Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
               Connection con=DriverManager.getConnection("jdbc:odbc:rock");
               Statement st=con.createStatement();
                dell=st.executeUpdate("delete from reminder where code='"+t2+"'");
               ResultSet rs20=st.executeQuery("Select dateadd(d,"+remin+",convert(varchar(12),getdate(),106))");
                                          
               while(rs20.next())
                {
                  remind=rs20.getString(1);
         
                }
                
              rs=st.executeUpdate("insert into treatement values("+t7+","+t6+",getdate(),'"+t2+"','"+t1+"','"+t3+"','"+t4+"',"+t8+","+pay+","+n+")"); 
              rs1=st.executeUpdate("insert into balance values("+t7+",'"+t2+"',"+t6+","+pay+","+n+")");
              if(remin>0)
              {    
              rem=st.executeUpdate("insert into reminder values('"+t2+"',convert(varchar(12),getdate(),106),'"+remind+"')"); 
              }
              else
              {
               rem=st.executeUpdate("insert into reminder values('"+t2+"',convert(varchar(12),getdate(),106),'"+reminds+"')");    
              }    
              if(t6>1)
               {
                    
                  zorro=st.executeUpdate("delete from balance where treatement_id <"+t6+" and code='"+t2+"'");
                  
               }
               remindr=st.executeUpdate("delete from reminder where dates1<convert(varchar(12),getdate(),106)");       
              JOptionPane.showMessageDialog(this,"Record Saved");
               
                btnsave.setEnabled(false);
                
                st.close();
                con.close();
           
              } 
                catch(SQLException sq)
                {
                 JOptionPane.showMessageDialog(this,"Database Error"+sq,"Treatement",JOptionPane.ERROR_MESSAGE);   
                  
               }
       
               catch(Exception e)
               {
                JOptionPane.showMessageDialog(this,"Error Occur"+e);   
               }
              }
        
        else if((t3.equals("")&&t4.equals("")&&t8==0))
        {
          
            lbldiesease.setText("Enter Disease");
    
            lbltreatement.setText("Enter Treatment");
        
            lbleamount.setText("Amount");
        }
         else if(t3.equals("")&&t4.equals(""))
          {
            lbltreatement.setText("Enter Treatment");
            lbldiesease.setText("Enter Disease");
             
           
          }
         else if(t4.equals("")&&t8==0)
         {
         
            lbltreatement.setText("Enter Treatment");
             lbleamount.setText("Amount");
            
         }
         else if(t3.equals("")&&t8==0)
         {
            lbldiesease.setText("Enter Disease");
            lbleamount.setText("Amount");
         }   
         else if(t3.equals(""))
         {
           lbldiesease.setText("Enter Disease");   
         }
         else if(t4.equals(""))
         {
             lbltreatement.setText("Enter Treatment"); 
         }    
         else if(t8==0)
         {
      
             lbleamount.setText("Amount");
         }
   
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtdieseaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdieseaseFocusGained
        // TODO add your handling code here:
		lbldiesease.setText("");
    }//GEN-LAST:event_txtdieseaseFocusGained
    private void txttreatementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttreatementFocusGained
		lbltreatement.setText("");
	}//GEN-LAST:event_txttreatementFocusGained

    private void txtamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusGained
		lbleamount.setText("");
	}//GEN-LAST:event_txtamountFocusGained

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        System.out.println("Click on print");
        name=txtname.getText();
//        t2=txtcode.getText();
        diesease=txtdiesease.getText();
        treatement=txttreatement.getText();
//        t6=Integer.parseInt(lblid.getText());
//        t7=Integer.parseInt(lblbill.getText());
        amount=Integer.parseInt(txtamount.getText()); 
        int pay=Integer.parseInt(txtpaid.getText());
        int balance=Integer.parseInt(txtbalance.getText());
        
        System.out.println("diesease : "+ diesease);
//        System.out.println("t2 : "+ t2);
//        System.out.println("t3 : "+ t3);
        System.out.println("treatement : "+ treatement);
        System.out.println("amount : "+ amount);
        System.out.println("balance : "+ balance);
        System.out.println("pay : "+ pay);
                
        try
        {
            InputStream is = this.getClass().getClassLoader().getResourceAsStream("clinic/rptSampleJasper.jasper");
            
            Map mapParameters=new HashMap();
            mapParameters.put("title", "Hospital");
//            mapParameters.put("fromDate", "01-01-2018");
//            mapParameters.put("toDate", "30-01-2018");
            
            
            
            
            
            List<clsDiseaseBean>listOfDiseaseBeans=new ArrayList<clsDiseaseBean>();
            
            clsDiseaseBean obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Name");
            obj.setStrDiseaseName(name);
            
            listOfDiseaseBeans.add(obj);
            
            obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Diesease");
            obj.setStrDiseaseName(diesease);
            
            listOfDiseaseBeans.add(obj);
            
            obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Treatement");
            obj.setStrDiseaseName(treatement);
            
            listOfDiseaseBeans.add(obj);
           
            obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Amount");
            obj.setStrDiseaseName(Integer.toString(amount));
            
            listOfDiseaseBeans.add(obj);
            
            obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Paid");
            obj.setStrDiseaseName(Integer.toString(pay));
            
            listOfDiseaseBeans.add(obj);
            
            obj=new clsDiseaseBean();
            obj.setStrDiseaseCode("Balance");
            obj.setStrDiseaseName(Integer.toString(balance));
            
            listOfDiseaseBeans.add(obj);

            JRBeanCollectionDataSource beanCollectionDataSource = new JRBeanCollectionDataSource(listOfDiseaseBeans);
            JasperPrint print = JasperFillManager.fillReport(is, mapParameters, beanCollectionDataSource);
            List<JRPrintPage> pages = print.getPages();

            JRViewer viewer = new JRViewer(print);
            JFrame jf = new JFrame();
            jf.getContentPane().add(viewer);
            jf.validate();
            jf.setVisible(true);
            jf.setSize(new Dimension(850, 750));

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_printActionPerformed
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblallergy;
    private javax.swing.JLabel lblamount;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lblcard;
    private javax.swing.JLabel lblcode;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldatedisplay;
    private javax.swing.JLabel lbldiesease;
    private javax.swing.JLabel lbleamount;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblreminder;
    private javax.swing.JLabel lbltreatement;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtallergy;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextArea txtdiesease;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpaid;
    private javax.swing.JTextArea txttreatement;
    // End of variables declaration//GEN-END:variables
    
}
