/*
 * inventory.java
 *
 * Created on July 10, 2012, 8:45 AM
 */

package clinic;

/**
 *
 * @author  Amir Sanas
 */
public class inventory extends javax.swing.JFrame {
     addtablet t=new addtablet();
     boolean tvi=t.isVisible();
     adddiesease d=new adddiesease();
     boolean dvi=d.isVisible();
    /** Creates new form inventory */
    public inventory() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntablet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnntablet = new javax.swing.JButton();
        btndiesease = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btntablet.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btntablet.setText("Tablet");
        btntablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabletActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory");
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.pink);

        btnback.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnback.setForeground(new java.awt.Color(0, 102, 0));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnntablet.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnntablet.setIcon(new javax.swing.ImageIcon("src/images/tablet.jpg")); // NOI18N
        btnntablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnntabletActionPerformed(evt);
            }
        });

        btndiesease.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btndiesease.setIcon(new javax.swing.ImageIcon("src/images/diseases.JPG")); // NOI18N
        btndiesease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndieseaseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36));
        jLabel1.setForeground(new java.awt.Color(105, 166, 105));
        jLabel1.setText("INVENTORY");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(btndiesease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(47, 47, 47)
                        .add(btnntablet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(98, 98, 98)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel1)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(btndiesease, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(btnntablet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(40, 40, 40)
                .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnntabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnntabletActionPerformed
// TODO add your handling code here:
             
       if(tvi==false)
       {    
       t.setVisible(true);
       tvi=true;
       }
       else
       {
        tvi=t.isVisible();
        if(tvi==false)
        {    
         t.setVisible(true);
         tvi=true;
        }
        else
        {
          t.requestFocus();  
        }    
       }   
        
       
    }//GEN-LAST:event_btnntabletActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
// TODO add your handling code here:
    t.setVisible(false);
    d.setVisible(false);
    this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btntabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabletActionPerformed
// TODO add your handling code here:
        
    }//GEN-LAST:event_btntabletActionPerformed

    private void btndieseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndieseaseActionPerformed
// TODO add your handling code here:
        
      
            
       if(dvi==false)
       {    
       d.setVisible(true);
       dvi=true;
       }
       else
       {
        dvi=d.isVisible();
        if(dvi==false)
        {    
         d.setVisible(true);
         dvi=true;
        }
        else
        {
          d.requestFocus();  
        }    
       }  
    }//GEN-LAST:event_btndieseaseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndiesease;
    private javax.swing.JButton btnntablet;
    private javax.swing.JButton btntablet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
