/*
 * login.java
 *
 * Created on January 16, 2012, 3:18 AM
 */

package clinic;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author  Administratorn
 */
public class login extends javax.swing.JFrame {
    Connection con; 
    /** Creates new form login */
    public login() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lblpasword = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnforget = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jPanel2.setBackground(java.awt.Color.pink);

        jPanel1.setBackground(java.awt.Color.pink);

        lblname.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblname.setText("USER NAME");

        lblpasword.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblpasword.setText("PASSWORD");

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14));

        btnlogin.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        lblimage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblimage.setDoubleBuffered(true);

        txtpassword.setName("txtpassword"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("src/images/login.jpg")); // NOI18N

        btnforget.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnforget.setText("Forget Password");
        btnforget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("WELCOME TO CLINIC MASTER");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(111, 111, 111)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(186, 186, 186)
                .add(lblimage)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblpasword)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblname))
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtname)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, btnforget, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(btnlogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(56, 56, 56)
                                .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(47, 47, 47)))
                .add(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblimage)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(23, 23, 23)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblpasword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(41, 41, 41)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnlogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)
                        .add(btnforget)))
                .add(44, 44, 44))
        );

        lblimage.getAccessibleContext().setAccessibleName("lblimage");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnforgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetActionPerformed
// TODO add your handling code here:       
        String t1="",t2="",t3="";
        t2=txtname.getText();
        if(!(t2.equals("")))
        {
         try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select hint,name from login where name='"+t2+"'");
                       
            while(rs.next())
           {   
            t1= rs.getString("hint");
            t3= rs.getString("name");
            }
            if((t2.equals(t3)))
            {
                JOptionPane.showMessageDialog(this,""+t1);
            }
            else
            {
        
            JOptionPane.showMessageDialog(this,"user name is wrong");
            txtname.setText("");
           }
            
            st.close();
            con.close();
        } 
         catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Login",JOptionPane.ERROR_MESSAGE);
            
         }       
            catch(Exception e) 
            {
             JOptionPane.showMessageDialog(this,"error occur"+e);
            }
        }
        else
        {
        JOptionPane.showMessageDialog(this,"Please Enter User Name");
        }
        
    }//GEN-LAST:event_btnforgetActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
// TODO add your handling code here:
        String st1,st2,t1="",t2="",t3="";
        st1=txtname.getText();
        st2=txtpassword.getText();
        String startdate="26-sep-2013",enddate="01-oct-2013";
        int num1=0,num4=0;
        
            try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
             con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from login where name='"+st1+"' and password='"+st2+"'");
                       
            while(rs.next())
           {
                t1= rs.getString("name").trim();
                t2=rs.getString("password").trim();
                t3=rs.getString("utype");
                
            }

            ResultSet rs2=st.executeQuery("select count(getdate()) where getdate()between '"+startdate+"'and'"+enddate+"'");
            while(rs2.next())
            {
             num1=rs2.getInt(1);  
            }
            ResultSet rs3=st.executeQuery("select count(code) from reminder where dates1=convert(varchar(12),getdate(),106)");
            while(rs3.next())
            {
             num4=rs3.getInt(1); 
             
            }   
            
            if (!(st1.equals("")||st2.equals("")))
            {
                if (!(st1.equals(t1) && st2.equals(t2)))
                {
                JOptionPane.showMessageDialog(this,"Wrong User Name or Password");
                 txtname.setText("");
                txtpassword.setText("");
                txtname.requestFocus(true);
                }
                else
                {
                     if(t3.equals("admin"))
                     { 
                       if(num1==1)
                        {
                         JOptionPane.showMessageDialog(this,"Expiry date is 01 OCT 2013");
                        }
                     
                         homepage h=new homepage();
                         h.setVisible(true);
                    
                     }
                     else
                     {
                      if(num1==1)
                        {
                         JOptionPane.showMessageDialog(this,"Expiry date is 01 OCT 2013");
                        }    
                      homepage_reception hmpg=new homepage_reception();
                      hmpg.setVisible(true);
                  
                     }  
                     this.dispose();
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(this,"UserName and Password must be required");
                txtname.setText("");
                txtpassword.setText("");
                txtname.requestFocus(true);//cus()setFocusable(true);
            }
                       
          
            st.close();
            con.close();
        } 
         catch(SQLException sq)
         {
         JOptionPane.showMessageDialog(this,"Database Error","Login",JOptionPane.ERROR_MESSAGE);              
         
         }        
         catch(Exception e)
         {
          JOptionPane.showMessageDialog(this,"error occur");
         }
        
       
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
// TODO add your handling code here:
    System.exit(1);    
    }//GEN-LAST:event_btnexitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       login log=new login();
       log.setVisible(true);
       log.setTitle("Login"); 
       log.pack();

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforget;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpasword;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
    
}
