/*
 * patientrecords.java
 *
 * Created on February 4, 2012, 9:25 PM
 */

package clinic;

import java.util.Vector;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author  Administrator
 *
 */

public class patientrecords extends javax.swing.JFrame {
   
    JTable jTable4;
       JScrollPane jScrollPane4;
    Connection con;
    /** Creates new form patientrecords */
    public patientrecords(String name,String allergy,String gender,String code,int age) {
        initComponents();
        
        txtname.setText(name);
        txtallergy.setText(allergy);
        txtgender.setText(gender);
        txtcode.setText(code);
        txtage.setText(""+age);
  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnopen = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblcode = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblallergy = new javax.swing.JLabel();
        txtallergy = new javax.swing.JTextField();
        lblrecord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Record's");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnopen.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnopen.setText("Open");
        btnopen.setName("btnopen"); // NOI18N
        btnopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnback.setText("Back");
        btnback.setName("btnback"); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Diesease", "Treatement", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblcode.setFont(new java.awt.Font("Times New Roman", 1, 14));
        lblcode.setText("CODE");
        lblcode.setName("lblcode"); // NOI18N

        txtcode.setEditable(false);
        txtcode.setFont(new java.awt.Font("Times New Roman", 1, 14));
        txtcode.setBorder(null);
        txtcode.setName("txtcode"); // NOI18N

        lblname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblname.setText("Name");
        lblname.setName("lblname"); // NOI18N

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtname.setBorder(null);
        txtname.setName("txtname"); // NOI18N

        lblgender.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblgender.setText("Gender");
        lblgender.setName("lblgender"); // NOI18N

        txtgender.setEditable(false);
        txtgender.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtgender.setBorder(null);
        txtgender.setName("txtgender"); // NOI18N

        lblage.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblage.setText("Age");
        lblage.setName("lblage"); // NOI18N

        txtage.setEditable(false);
        txtage.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtage.setBorder(null);
        txtage.setName("txtage"); // NOI18N

        lblallergy.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblallergy.setText("Allergy");
        lblallergy.setName("lblallergy"); // NOI18N

        txtallergy.setEditable(false);
        txtallergy.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtallergy.setBorder(null);
        txtallergy.setName("txtallergy"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblname)
                    .add(lblallergy)
                    .add(lblgender))
                .add(46, 46, 46)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblage)
                    .add(lblcode))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblname)
                    .add(lblcode)
                    .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblgender))
                        .add(16, 16, 16)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblallergy)
                            .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblage))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblrecord.setFont(new java.awt.Font("Times New Roman", 1, 24));
        lblrecord.setForeground(new java.awt.Color(0, 102, 0));
        lblrecord.setText("PATIENT RECORDS");
        lblrecord.setName("lblrecord"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                                .add(199, 199, 199)
                                .add(btnopen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(57, 57, 57)
                                .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                                .add(20, 20, 20)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jScrollPane1)
                                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(279, 279, 279)
                        .add(lblrecord)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblrecord, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 413, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnopen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
    // TODO add your handling code here:
        
         this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenActionPerformed
      // TODO add your handling code here: 
      
     String name,allergy,gender,code;
     int age; 
     name=txtname.getText();
     allergy=txtallergy.getText();
     gender=txtgender.getText();
     code=txtcode.getText();
     age=Integer.parseInt(txtage.getText());
     
     String s="",z="";
    int q=jTable4.getRowCount();
    int p=jTable4.getColumnCount();
    int i=jTable4.getSelectedRow();
    int j=jTable4.getSelectedColumn();
    int b=i+1;
    if(i < 0 && j < 0)
    {
     JOptionPane.showMessageDialog(this,"No Record Selected");
    }
    else
    {
    Object u=jTable4.getValueAt(i,0);
    Object o=jTable4.getValueAt(i,1);
    s=o.toString();
    z=u.toString();

     
            try{

                   Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                   con=DriverManager.getConnection("jdbc:odbc:rock");
                   Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("select name,code,diesease,treatement,dates,treatement_id from treatement where dates='"+s+"'");
                       while(rs.next())
                           {
                              String treatement,diesease,visit;    
                              Date date;
                              diesease=rs.getString("diesease");
                              treatement=rs.getString("treatement");
                              date=rs.getDate("dates");
                              visit=rs.getString("treatement_id");
                              history_card hc=new history_card(name,allergy,gender,code,age,date,visit,diesease,treatement,q,i,z);
                              hc.setVisible(true);
                           }
                  st.close();
                  con.close();
               }
            
          catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Treatement",JOptionPane.ERROR_MESSAGE);
            
         } 
               catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,"Error"+e);
          
         }  
         }
    }//GEN-LAST:event_btnopenActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
        
       String t1=txtcode.getText();
       int i;
       Vector columnnames=new Vector();
       Vector data=new Vector();
       JTable jTable3;
       JScrollPane jScrollPane3;
       JPanel panel=new JPanel();
             try
                {
                   Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                   con=DriverManager.getConnection("jdbc:odbc:rock");
     
         Statement st=con.createStatement();
         ResultSet rs;
         rs=st.executeQuery("select treatement_id as Visit_No, dates as Date_Time,diesease as Disease,treatement as Treatment,amount as Amount,paid as Paid,balance as Balance from treatement where code='"+t1+"' order by Date_Time desc");
         ResultSetMetaData md=rs.getMetaData();
         int columns=md.getColumnCount();
         for(i=1;i<=columns;i++)
          {
             columnnames.addElement(md.getColumnName(i));
          }
         while(rs.next())
          {
              Vector row=new Vector(columns);
               for(i=1;i<=columns;i++)
                 {
                   row.addElement(rs.getObject(i));
                 }
              data.addElement(row);
         }
   
        st.close();
        con.close();
        }
     catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Treatment",JOptionPane.ERROR_MESSAGE);
            this.dispose();
         } 
               catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,"Error"+e);
          this.dispose();
         }
      jTable4=new JTable(data,columnnames);
      jScrollPane4=new JScrollPane(jTable4);
      jTable1.setCellEditor(jTable4.getCellEditor());
      jScrollPane1.setViewportView(jTable4);

        
    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnopen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblallergy;
    private javax.swing.JLabel lblcode;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblrecord;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtallergy;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
    
}
