/*
 * personal.java
 *
 * Created on January 29, 2012, 12:41 PM
 */

package clinic;

/**
 *
 * @author  Administrator
 */

import javax.swing.*;
import java.sql.*;


public class personal extends javax.swing.JFrame {
    
    /** Creates new form personal */
    public personal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblcuname = new javax.swing.JLabel();
        lblnuname = new javax.swing.JLabel();
        cnuname = new javax.swing.JLabel();
        btncreate1 = new javax.swing.JButton();
        txtcuname = new javax.swing.JTextField();
        txtnuname = new javax.swing.JTextField();
        txtcnuname = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblcpassword = new javax.swing.JLabel();
        lblnpassword = new javax.swing.JLabel();
        lblcnpassword = new javax.swing.JLabel();
        btncreate2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtusername1 = new javax.swing.JTextField();
        txtcpassword = new javax.swing.JPasswordField();
        txtnpassword = new javax.swing.JPasswordField();
        txtcnpassword = new javax.swing.JPasswordField();
        lblpassword = new javax.swing.JLabel();
        lblsetting = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthint = new javax.swing.JTextArea();
        btnok = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        lblhint = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personal Setting");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)));

        lblcuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblcuname.setText("Current User Name");
        lblcuname.setName("lblcuname"); // NOI18N

        lblnuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblnuname.setText("New User Name");
        lblnuname.setName("lblnuname"); // NOI18N

        cnuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cnuname.setText("Confirm New User Name");
        cnuname.setName("lblcnuname"); // NOI18N

        btncreate1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btncreate1.setText("Create");
        btncreate1.setName("btncreate1"); // NOI18N
        btncreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreate1ActionPerformed(evt);
            }
        });

        txtcuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcuname.setName("txtcuname"); // NOI18N

        txtnuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtnuname.setName("txtnuname"); // NOI18N

        txtcnuname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcnuname.setName("txtcnuname"); // NOI18N

        lblname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblname.setForeground(new java.awt.Color(255, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(lblname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(lblcuname)
                                .add(lblnuname)
                                .add(cnuname))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(txtnuname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, txtcuname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .add(txtcnuname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(btncreate1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblcuname)
                    .add(txtcuname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtnuname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cnuname)
                            .add(txtcnuname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(lblnuname))
                .add(26, 26, 26)
                .add(lblname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45)
                .add(btncreate1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)));

        lblcpassword.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblcpassword.setText("Current Password");
        lblcpassword.setName("lblcpassword"); // NOI18N

        lblnpassword.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblnpassword.setText("New Password");
        lblnpassword.setName("lblnpassword"); // NOI18N

        lblcnpassword.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblcnpassword.setText("Confirm New Password");
        lblcnpassword.setName("lblcnpassword"); // NOI18N

        btncreate2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btncreate2.setText("Create");
        btncreate2.setName("btncreate2"); // NOI18N
        btncreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreate2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel1.setText("User Name");

        txtusername1.setName("txtusername1"); // NOI18N

        txtcpassword.setName("txtcpassword"); // NOI18N

        txtnpassword.setName("txtnpassword"); // NOI18N

        txtcnpassword.setName("txtcnpassword"); // NOI18N

        lblpassword.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblpassword.setForeground(new java.awt.Color(255, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(lblpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jPanel2Layout.createSequentialGroup()
                                            .add(lblcpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(51, 51, 51))
                                        .add(jPanel2Layout.createSequentialGroup()
                                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(lblnpassword)
                                        .add(67, 67, 67))))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(lblcnpassword)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtusername1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtcpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtnpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .add(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtcnpassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                        .addContainerGap())))
            .add(jPanel2Layout.createSequentialGroup()
                .add(88, 88, 88)
                .add(btncreate2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtusername1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .add(31, 31, 31)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblcpassword)
                    .add(txtcpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblnpassword)
                    .add(txtnpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblcnpassword)
                    .add(txtcnpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(lblpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(btncreate2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblsetting.setFont(new java.awt.Font("Algerian", 1, 36));
        lblsetting.setForeground(new java.awt.Color(0, 102, 51));
        lblsetting.setText("SECURITY");
        lblsetting.setName("lblsetting"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hint", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)));

        txthint.setColumns(20);
        txthint.setFont(new java.awt.Font("Courier New", 0, 13));
        txthint.setLineWrap(true);
        txthint.setRows(5);
        txthint.setName("txthint"); // NOI18N
        jScrollPane1.setViewportView(txthint);

        btnok.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnok.setText("Create");
        btnok.setName("btnok"); // NOI18N
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        txtusername.setName("txtusername"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel2.setText("User Name");

        txtpassword1.setName("txtpassword1"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel3.setText("Password");

        lblhint.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblhint.setForeground(new java.awt.Color(255, 51, 0));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(lblhint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                        .add(65, 65, 65)
                        .add(btnok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtpassword1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .add(txtusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtpassword1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblhint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnexit1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        btnexit1.setText("Close");
        btnexit1.setName("btnexit1"); // NOI18N
        btnexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblsetting)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .add(btnexit1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(375, 375, 375))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(lblsetting)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(22, 22, 22)
                .add(btnexit1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
// TODO add your handling code here:
        String t1,t2,t3,t4,name="",pass="";
        t1=txthint.getText();
        t2=txtusername.getText();
        t3=txtpassword1.getText();
       if (!(t2.equals("")||t3.equals("")||t1.equals("")))
       {     
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select name,password from login where password='"+t3+"'and name='"+t2+"'");                     
            while(rs.next())
             {
               name= rs.getString("name").trim();
                pass=rs.getString("password").trim();
             }
             if (!(t2.equals(name) && t3.equals(pass)))
                 {
                  lblhint.setText("Wrong User Name Or Password");
                  txtusername.setText("");
                  txtpassword1.setText("");
                  txthint.setText("");
                  txtusername.requestFocus(true);
                 }
                else
                 { 
                     int s=st.executeUpdate("Update login set hint='"+t1+"' where name='"+t2+"' and password='"+t3+"'");
                     JOptionPane.showMessageDialog(this,"Record Is Updated");
                      txtusername.setText("");
                txtpassword1.setText("");
                txthint.setText("");
                this.dispose();
                 }  
     
            st.close();
            con.close();
           } 
          catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Login",JOptionPane.ERROR_MESSAGE);
            
         } 
               catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,"Error"+e);
          this.dispose();
         }
            } 
            else 
            {
                lblhint.setText("All Field Of Hint Must Filled");
                txtusername.setText("");
                txtpassword1.setText("");
                txthint.setText("");
                txtusername.requestFocus(true);//cus()setFocusable(true);
            }   

    }//GEN-LAST:event_btnokActionPerformed

    private void btnexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit1ActionPerformed
// TODO add your handling code here:
      this.dispose();    
    }//GEN-LAST:event_btnexit1ActionPerformed

    private void btncreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreate2ActionPerformed
// TODO add your handling code here:
        
                String p4="",p1,p2,p3,p5,p6=""; 
      
        p1=txtcpassword.getText();
        p2=txtnpassword.getText();
        p3=txtcnpassword.getText();
        p5=txtusername1.getText();
       
       if(!(p5.equals("")||p1.equals("")||p2.equals("")||p3.equals("")))
        {    
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();                     
            ResultSet rs=st.executeQuery("select name,password from login where password='"+p1+"'and name='"+p5+"'");                     
            while(rs.next())
           {
                p6=rs.getString("name");
                p4=rs.getString("password");
           }            
            if(p1.equals(p4)&&p5.equals(p6)) 
            {  
                if(p2.equals(p3))  
                {     
                  int len=p2.length();
                  if(len>0&&len<20)
                  { 
                      int s=st.executeUpdate("Update login set password='"+p2+"' where password='"+p1+"'and name='"+p5+"'");
                      JOptionPane.showMessageDialog(this,"Record Is Updated");
                      this.dispose();
                  }
                  else
                  {
                      lblpassword.setText("Password Must Be More Than 5 Letter");                       
                       txtnpassword.setText("");
                       txtcnpassword.setText(""); 
                  }
                }   
               else
                 {
                  lblpassword.setText("Wrong New Password");
                  txtnpassword.setText("");
                 txtcnpassword.setText("");
                  } 
             }
            else
            {
              lblpassword.setText("Wrong Current Password Or User Name");
                txtusername1.setText("");
                txtcpassword.setText("");
            }
            st.close();
            con.close();
           }
        catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Login",JOptionPane.ERROR_MESSAGE);
         
         } 
               catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,"Error"+e);
     
         }
       }
        else
        {
            lblpassword.setText("All Field Of Password Must Fill");
            txtusername1.setText("");
            txtcpassword.setText("");
            txtnpassword.setText("");
            txtcnpassword.setText("");
        }     
        
    }//GEN-LAST:event_btncreate2ActionPerformed

    private void btncreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreate1ActionPerformed
// TODO add your handling code here:
        
        String t1,t2,t3,t4=""; 
        t1=txtcuname.getText();
        t2=txtnuname.getText();
        t3=txtcnuname.getText();
        if(!(t1.equals("")||t2.equals("")||t3.equals("")))
        {    
         try
          {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:rock");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select name from login where name='"+t1+"'");
                       
            while(rs.next())
           {
                t4= rs.getString("name").trim();
            }  
           
            if(t1.equals(t4)) 
            {    
              if(t2.equals(t3))
              {    
               int r=st.executeUpdate("Update login set name='"+t2+"' where name='"+t1+"'");
                JOptionPane.showMessageDialog(this,"Record is updated");
                txtcuname.setText("");
                txtnuname.setText("");
                txtcnuname.setText("");
              }
              else
              {
                 lblname.setText("New User Name Is Different");  
                txtnuname.setText("");
                txtcnuname.setText(""); 
              }   
            }
            else
            {
                lblname.setText("Wrong Current User Name");  
                txtcuname.setText("");
            }
            st.close();
            con.close();
        }
        
         catch(SQLException sq)
         {
            JOptionPane.showMessageDialog(this,"Database Error","Login",JOptionPane.ERROR_MESSAGE);
         
         } 
               catch(Exception e)
         {
         JOptionPane.showMessageDialog(this,"Error"+e);
     
         }
        
     
       }
        else
        {
            lblname.setText("All The Field Of User Name Must Be Required");
        }    
        
    }//GEN-LAST:event_btncreate1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate1;
    private javax.swing.JButton btncreate2;
    private javax.swing.JButton btnexit1;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel cnuname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcnpassword;
    private javax.swing.JLabel lblcpassword;
    private javax.swing.JLabel lblcuname;
    private javax.swing.JLabel lblhint;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnpassword;
    private javax.swing.JLabel lblnuname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblsetting;
    private javax.swing.JPasswordField txtcnpassword;
    private javax.swing.JTextField txtcnuname;
    private javax.swing.JPasswordField txtcpassword;
    private javax.swing.JTextField txtcuname;
    private javax.swing.JTextArea txthint;
    private javax.swing.JPasswordField txtnpassword;
    private javax.swing.JTextField txtnuname;
    private javax.swing.JPasswordField txtpassword1;
    private javax.swing.JTextField txtusername;
    private javax.swing.JTextField txtusername1;
    // End of variables declaration//GEN-END:variables
    
}
