/*
 * update_record.java
 *
 * Created on March 2, 2012, 12:07 PM
 */

package clinic;

/**
 *
 * @author  Administrator
 */

import javax.swing.*;
import java.sql.*;

public class update_record extends javax.swing.JFrame {
    
    /** Creates new form update_record */
    public update_record(String a,String b,String c,String d,String f,String g,String h,String k,String l,String m,String n,String o,String p,int e) {
        initComponents();
        
       txtfname.setText(a);
       txtmname.setText(b);
       txtlname.setText(c);
       txtbirth.setText(d);  
       txtage.setText(""+e);
       txtgender.setText(f);
       txtoccupation.setText(g);
       txtaddress.setText(h);
       txtcontact.setText(k);
       txtmail.setText(l);
       txtcode.setText(o);
       txtallergy.setText(p);
       txtreference.setText(m);
       txtrelation.setText(n);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblpatient = new javax.swing.JLabel();
        lblfname = new javax.swing.JLabel();
        lblmname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblbirth = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lbloccupation = new javax.swing.JLabel();
        txtoccupation = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtbirth = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbladdress = new javax.swing.JLabel();
        lblcontact = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtcontact = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblcode = new javax.swing.JLabel();
        lblreference = new javax.swing.JLabel();
        txtreference = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        lblrelation = new javax.swing.JLabel();
        txtrelation = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblallergy = new javax.swing.JLabel();
        txtallergy = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblpatient.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblpatient.setText("Name Of Patient");
        lblpatient.setName("lblpatient"); // NOI18N

        lblfname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblfname.setText("F-Name");
        lblfname.setName("lblfname"); // NOI18N

        lblmname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblmname.setText("M-Name");
        lblmname.setName("lblmname"); // NOI18N

        lbllname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lbllname.setText("L-Name");
        lbllname.setName("lbllname"); // NOI18N

        txtfname.setEditable(false);
        txtfname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtfname.setName("txtfname"); // NOI18N

        txtmname.setEditable(false);
        txtmname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmname.setName("txtmname"); // NOI18N

        txtlname.setEditable(false);
        txtlname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtlname.setName("txtlname"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblpatient)
                        .add(37, 37, 37)
                        .add(txtfname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(19, 19, 19)
                        .add(txtmname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(22, 22, 22)
                        .add(txtlname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(147, 147, 147)
                        .add(lblfname)
                        .add(150, 150, 150)
                        .add(lblmname)
                        .add(117, 117, 117)
                        .add(lbllname)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblpatient)
                    .add(txtfname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtmname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtlname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblfname)
                    .add(lblmname)
                    .add(lbllname))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblbirth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblbirth.setText("Date Of Birth");
        lblbirth.setName("lblbirth"); // NOI18N

        lblgender.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblgender.setText("Gender");
        lblgender.setName("lblgender"); // NOI18N

        lblage.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblage.setText("Age");
        lblage.setName("lblage"); // NOI18N

        lbloccupation.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lbloccupation.setText("Occupation");
        lbloccupation.setName("lbloccupation"); // NOI18N

        txtoccupation.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtoccupation.setName("txtoccupation"); // NOI18N
        txtoccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoccupationKeyReleased(evt);
            }
        });

        txtage.setEditable(false);
        txtage.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtage.setName("txtage"); // NOI18N

        txtgender.setEditable(false);
        txtgender.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtgender.setName("txtgender"); // NOI18N

        txtbirth.setEditable(false);
        txtbirth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtbirth.setName("txtbirth"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblbirth)
                    .add(lblgender))
                .add(54, 54, 54)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtbirth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(lbloccupation)
                        .add(13, 13, 13))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(lblage)
                        .add(21, 21, 21)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtoccupation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblbirth)
                            .add(txtbirth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblgender)
                            .add(txtgender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(txtage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblage))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lbloccupation)
                            .add(txtoccupation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbladdress.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lbladdress.setText("Address");
        lbladdress.setName("lbladdress"); // NOI18N

        lblcontact.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblcontact.setText("Contact No.");
        lblcontact.setName("lblcontact"); // NOI18N

        lblmail.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblmail.setText("E-Mail");
        lblmail.setName("lblmail"); // NOI18N

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtaddress.setLineWrap(true);
        txtaddress.setRows(5);
        txtaddress.setName("txtaddress"); // NOI18N
        jScrollPane1.setViewportView(txtaddress);

        txtcontact.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcontact.setName("txtcontact"); // NOI18N
        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontactKeyReleased(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmail.setName("txtmail"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(lbladdress)
                .add(14, 14, 14)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblmail)
                    .add(lblcontact))
                .add(7, 7, 7)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtcontact, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtcontact, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblcontact))
                .add(29, 29, 29)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblmail))
                .addContainerGap())
            .add(jPanel3Layout.createSequentialGroup()
                .add(49, 49, 49)
                .add(lbladdress)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblcode.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblcode.setText("Code");
        lblcode.setName("lblcode"); // NOI18N

        lblreference.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblreference.setText("Reference");
        lblreference.setName("lblreference"); // NOI18N

        txtreference.setEditable(false);
        txtreference.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtreference.setName("txtreference"); // NOI18N

        txtcode.setEditable(false);
        txtcode.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcode.setName("txtcode"); // NOI18N

        lblrelation.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblrelation.setText("Relation");
        lblrelation.setName("lblrelation"); // NOI18N

        txtrelation.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtrelation.setEnabled(false);
        txtrelation.setName("txtrelation"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(lblcode)
                .add(32, 32, 32)
                .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(72, 72, 72)
                .add(lblreference)
                .add(48, 48, 48)
                .add(txtreference, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(69, 69, 69)
                .add(lblrelation)
                .add(53, 53, 53)
                .add(txtrelation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblcode)
                    .add(txtcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblreference)
                    .add(txtreference, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblrelation)
                    .add(txtrelation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblallergy.setFont(new java.awt.Font("Times New Roman", 0, 14));
        lblallergy.setText("Allergy");
        lblallergy.setName("lblallergy"); // NOI18N

        txtallergy.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtallergy.setName("txtallergy"); // NOI18N
        txtallergy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtallergyKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(lblallergy)
                .add(24, 24, 24)
                .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 520, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblallergy)
                    .add(txtallergy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );

        btnupdate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnupdate.setText("Update");
        btnupdate.setName("btnupdate"); // NOI18N
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnexit.setText("Back");
        btnexit.setName("btnexit"); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("UPDATE  RECORD");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(234, 234, 234)
                        .add(jLabel1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(158, 158, 158)
                        .add(btnupdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(123, 123, 123)
                        .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(16, 16, 16)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnupdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtallergyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtallergyKeyReleased
// TODO add your handling code here:
                      String s=txtallergy.getText();
        int a=s.length()-1;
        int i=(int)s.charAt(a);
        if(!((i>64&&i<91)||(i>95&&i<123)))
        {
            JOptionPane.showMessageDialog(this,"Enter only Character","Warning",JOptionPane.WARNING_MESSAGE);
            txtallergy.setText("");
        }
    }//GEN-LAST:event_txtallergyKeyReleased

    private void txtcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyReleased
// TODO add your handling code here:
        
                String s=txtcontact.getText();
        if(!(s.equals("")))
        {
         int a=s.length()-1;
         int i=(int)s.charAt(a);
         if(!(i>47&&i<58))
        {
            JOptionPane.showMessageDialog(this,"Enter only number","Warning",JOptionPane.WARNING_MESSAGE);
            txtcontact.setText("");

         }
         else
          {
             if(s.length()>11)
                 {
                   JOptionPane.showMessageDialog(this,"Invalid Contact Number");  
                   txtcontact.setText("");
                  }
         }
       }
    
    }//GEN-LAST:event_txtcontactKeyReleased

    private void txtoccupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoccupationKeyReleased
// TODO add your handling code here:
                    String s=txtoccupation.getText();
        int a=s.length()-1;
        int i=(int)s.charAt(a);
        if(!((i>64&&i<91)||(i>95&&i<123)))
        {
            JOptionPane.showMessageDialog(this,"Enter only Character","Warning",JOptionPane.WARNING_MESSAGE);
            txtoccupation.setText("");
        }
    }//GEN-LAST:event_txtoccupationKeyReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
// TODO add your handling code here:
                String s1,s2,s3,s4,s5,s6,s7,s8;
       int  i1;    
       s1=txtoccupation.getText();
       s2=txtaddress.getText();
       s3=txtcontact.getText();
       s4=txtmail.getText();
       s5=txtallergy.getText();
       s6=txtcode.getText();
       s7=txtreference.getText();
       s8=txtrelation.getText();
        try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:rock");
        Statement st=con.createStatement();        
        int a=st.executeUpdate("update register set occupation='"+s1+"', address='"+s2+"',contact='"+s3+"', mail='"+s4+"',allergy='"+s5+"',reference='"+s7+"',relation='"+s8+"' where code='"+s6+"'");
        if(a>0)
        {
            JOptionPane.showMessageDialog(this,"Data Updated");
            this.dispose();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Unable to Updated data!!!!!");
        }
         st.close();
        con.close();
     }
         catch(SQLException sq)
         {
              JOptionPane.showMessageDialog(this,"Database Disconnected","Database Error",JOptionPane.ERROR_MESSAGE);   
              this.dispose(); 
         } 
         catch(Exception e)
         {
          JOptionPane.showMessageDialog(this,"There Is Any Error Occur ","Error",JOptionPane.ERROR_MESSAGE);  
          this.dispose();
         }
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
// TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnexitActionPerformed
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblallergy;
    private javax.swing.JLabel lblbirth;
    private javax.swing.JLabel lblcode;
    private javax.swing.JLabel lblcontact;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblmname;
    private javax.swing.JLabel lbloccupation;
    private javax.swing.JLabel lblpatient;
    private javax.swing.JLabel lblreference;
    private javax.swing.JLabel lblrelation;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtallergy;
    private javax.swing.JTextField txtbirth;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtreference;
    private javax.swing.JTextField txtrelation;
    // End of variables declaration//GEN-END:variables
    
}
